### ISSUE TITLE
KeyError 'objectClass'

### ISSUE THREAD

**Issue by compumatter** [VicentGJ/AD-webmanager#109]
Hello there,

Installed the software and am able to see this url fine:
![image](https://github.com/VicentGJ/AD-webmanager/assets/121611/b7182a31-1ea8-432f-ad92-9d73b5ce5220)

However, when I click Users I get this :
`
KeyError
KeyError: 'objectClass'

Traceback (most recent call last)
File "/SM_DATA/working/adwebmanager/venv/lib/python3.10/site-packages/flask/app.py", line 2091, in __call__
return self.wsgi_app(environ, start_response)
File "/SM_DATA/working/adwebmanager/venv/lib/python3.10/site-packages/flask/app.py", line 2076, in wsgi_app
response = self.handle_exception(e)
File "/SM_DATA/working/adwebmanager/venv/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/SM_DATA/working/adwebmanager/venv/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/SM_DATA/working/adwebmanager/venv/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/SM_DATA/working/adwebmanager/venv/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/SM_DATA/working/adwebmanager/libs/ldap_func.py", line 630, in _decorator
return view_func(*args, **kwargs)
File "/SM_DATA/working/adwebmanager/plugins/tree.py", line 84, in tree_base
entries = get_entries("top", "objectClass", base, scope)
File "/SM_DATA/working/adwebmanager/plugins/tree.py", line 166, in get_entries
other_entries = sorted(other_entries, key=lambda entry: entry['name'])
File "/SM_DATA/working/adwebmanager/plugins/tree.py", line 165, in <lambda>
other_entries = filter(lambda entry: 'user' not in entry['objectClass'], entries)
KeyError: 'objectClass'
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
`
http://192.168.9.133:8080/tree brings up a similar error.

I am using samba-ad-dc and using samba as my ldap environment not OpenLDAP.  

Any ideas of how to troubleshoot this?   I am using LDAP / AD logins successfully with many other products.

Thanks.

Jay
CompuMatter / ServerMatter

**Comment by JRGonz** [comment]
Same exact error for me as well. I can access the user I login as but nothing else.

**Comment by VicentGJ** [comment]
Sorry for the delay, I solved it in the master branch testing against my environment. Feel free to reopen this issue or create a new one if you find further problems.
