### ISSUE TITLE
Attribute not updating properly in user edit

### ISSUE THREAD

**Issue by Carlos-err406** [VicentGJ/AD-webmanager#94]
Username not being edited -> distinguishedName not being edited

2022-08-27 13:10:39 | ERROR | Got an exception
Traceback (most recent call last):
  File "/home/carlos/github/AD-webmanager/plugins/user.py", line 415, in user_edit_profile
    ldap_update_attribute(user['distinguishedName'], "distinguishedName", value)
  File "/home/carlos/github/AD-webmanager/libs/ldap_func.py", line 366, in ldap_update_attribute
    connection.rename_s(dn, value, new_parent)
  File "/home/carlos/github/AD-webmanager/venv/lib/python3.8/site-packages/ldap/ldapobject.py", line 481, in rename_s
    resp_type, resp_data, resp_msgid, resp_ctrls = self.result3(msgid,all=1,timeout=self.timeout)
  File "/home/carlos/github/AD-webmanager/venv/lib/python3.8/site-packages/ldap/ldapobject.py", line 543, in result3
    resp_type, resp_data, resp_msgid, decoded_resp_ctrls, retoid, retval = self.result4(
  File "/home/carlos/github/AD-webmanager/venv/lib/python3.8/site-packages/ldap/ldapobject.py", line 553, in result4
    ldap_result = self._ldap_call(self._l.result4,msgid,all,timeout,add_ctrls,add_intermediates,add_extop)
  File "/home/carlos/github/AD-webmanager/venv/lib/python3.8/site-packages/ldap/ldapobject.py", line 128, in _ldap_call
    result = func(*args,**kwargs)
ldap.OTHER: {'msgtype': 109, 'msgid': 10, 'result': 80, 'desc': 'Other (e.g., implementation specific) error', 'ctrls': [], 'info': '00002095: Other'}

**Comment by Carlos-err406** [comment]
connection.rename_s isn't updating distinguished name when sAMAccountName is edited, instead is throwing that error

**Comment by Carlos-err406** [comment]
problem was that to rename the distinguishedName, the rename_s()'s value parameter has to be the RDN
